
name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ mtrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ jodikalin8@gmail.com }}

    - name: Build
      run: |
        npm install
        grunt
